import { ProgramStatus, OrganizationType } from '@prisma/client';
import { evaluateEligibilityGate } from '../eligibility-gate';

const baseProgram = {
  id: 'p1',
  agencyId: 'NTIS',
  title: '지정과제 테스트',
  description: null,
  announcementUrl: 'https://example.com',
  targetType: [OrganizationType.COMPANY],
  minTrl: null,
  maxTrl: null,
  eligibilityCriteria: null,
  budgetAmount: null,
  fundingPeriod: null,
  deadline: null,
  category: null,
  keywords: [],
  contentHash: 'hash',
  status: ProgramStatus.ACTIVE,
  publishedAt: null,
  applicationStart: null,
  scrapedAt: new Date(),
  lastCheckedAt: new Date(),
  scrapingSource: 'TEST',
  createdAt: new Date(),
  updatedAt: new Date(),
  announcementType: 'R_D_PROJECT',
  announcingAgency: null,
  ministry: null,
  trlClassification: null,
  trlConfidence: null,
  allowedBusinessStructures: [],
  attachmentUrls: [],
  trlInferred: false,
  requiredCertifications: [],
  preferredCertifications: [],
  requiredMinEmployees: null,
  requiredMaxEmployees: null,
  requiredMinRevenue: null,
  requiredMaxRevenue: null,
  requiredInvestmentAmount: null,
  requiredOperatingYears: null,
  maxOperatingYears: null,
  requiresResearchInstitute: false,
  eligibilityConfidence: 'LOW',
  manualReviewRequired: false,
  manualReviewNotes: null,
  manualReviewCompletedAt: null,
  manualReviewCompletedBy: null,
  eligibilityLastUpdated: null,
  primaryTargetIndustry: null,
  secondaryTargetIndustries: [],
  semanticSubDomain: null,
  technologyDomainsSpecific: [],
  targetCompanyProfile: null,
  programIntent: null,
  semanticConfidence: 0,
  semanticEnrichedAt: null,
  semanticEnrichmentModel: null,
  idealApplicantProfile: null,
  idealProfileGeneratedAt: null,
  idealProfileVersion: null,
} as any;

const baseOrg = {
  id: 'o1',
  type: OrganizationType.COMPANY,
  name: 'Test Org',
  businessNumberEncrypted: 'x',
  businessNumberHash: 'y',
  profileCompleted: true,
  rdExperience: true,
  certifications: [],
  keyTechnologies: [],
  technologyDomainsSpecific: [],
  researchFocusAreas: [],
  createdAt: new Date(),
  updatedAt: new Date(),
} as any;

test('blocks designated projects', () => {
  const result = evaluateEligibilityGate(baseProgram, baseOrg);
  expect(result.passed).toBe(false);
  expect(result.blockReasons).toContain('DESIGNATED_PROJECT');
});
