import { ProgramStatus, OrganizationType } from '@prisma/client';
import { generateMatchesV6 } from '../funnel';

test('generates match for compatible ICT program', () => {
  const org = {
    id: 'o1',
    type: OrganizationType.COMPANY,
    name: 'Innowave',
    industrySector: 'ICT',
    rdExperience: true,
    keyTechnologies: ['AI', '데이터'],
    technologyDomainsSpecific: ['AI'],
    researchFocusAreas: ['데이터'],
    profileCompleted: true,
  } as any;

  const program = {
    id: 'p1',
    agencyId: 'NTIS',
    title: 'AI 데이터 플랫폼 기술개발',
    description: null,
    announcementUrl: 'https://example.com',
    targetType: [OrganizationType.COMPANY],
    minTrl: null,
    maxTrl: null,
    eligibilityCriteria: null,
    budgetAmount: BigInt(100000000),
    fundingPeriod: null,
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
    category: 'ICT',
    keywords: ['AI', '데이터'],
    contentHash: 'hash',
    status: ProgramStatus.ACTIVE,
    publishedAt: null,
    applicationStart: new Date(),
    scrapedAt: new Date(),
    lastCheckedAt: new Date(),
    scrapingSource: 'TEST',
    createdAt: new Date(),
    updatedAt: new Date(),
    announcementType: 'R_D_PROJECT',
    announcingAgency: null,
    ministry: '과학기술정보통신부',
    trlClassification: null,
    trlConfidence: null,
    allowedBusinessStructures: [],
    attachmentUrls: [],
    trlInferred: false,
    requiredCertifications: [],
    preferredCertifications: [],
    requiredMinEmployees: null,
    requiredMaxEmployees: null,
    requiredMinRevenue: null,
    requiredMaxRevenue: null,
    requiredInvestmentAmount: null,
    requiredOperatingYears: null,
    maxOperatingYears: null,
    requiresResearchInstitute: false,
    eligibilityConfidence: 'LOW',
    manualReviewRequired: false,
    manualReviewNotes: null,
    manualReviewCompletedAt: null,
    manualReviewCompletedBy: null,
    eligibilityLastUpdated: null,
    primaryTargetIndustry: null,
    secondaryTargetIndustries: [],
    semanticSubDomain: null,
    technologyDomainsSpecific: [],
    targetCompanyProfile: null,
    programIntent: null,
    semanticConfidence: 0,
    semanticEnrichedAt: null,
    semanticEnrichmentModel: null,
    idealApplicantProfile: null,
    idealProfileGeneratedAt: null,
    idealProfileVersion: null,
  } as any;

  const results = generateMatchesV6(org, [program], 3, { minimumScore: 0 });
  expect(results.length).toBe(1);
  expect(results[0].programId).toBe('p1');
});
