name: Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  deploy-preview:
    name: Deploy PR Preview
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
        env:
          SKIP_ENV_VALIDATION: true
      
      - name: Comment PR with preview info
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;
            const comment = `
            ## 🚀 Preview Deployment
            
            **Status:** ✅ Build successful
            **PR:** #${prNumber}
            **Commit:** ${context.sha.substring(0, 7)}
            **Branch:** ${context.payload.pull_request.head.ref}
            
            ### Preview Environment
            \`\`\`bash
            # To test locally:
            git fetch origin pull/${prNumber}/head:pr-${prNumber}
            git checkout pr-${prNumber}
            npm install
            npm run dev
            \`\`\`
            
            ### Build Info
            - **Node Version:** 20.x
            - **Build Time:** ${new Date().toISOString()}
            - **Triggered by:** @${context.actor}
            `;
            
            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  cleanup-preview:
    name: Cleanup Preview
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `
            ## 🧹 Preview Cleanup
            
            Preview environment has been cleaned up after PR ${context.payload.pull_request.merged ? 'merge' : 'close'}.
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

